// VoxLink — Arabic Strings

const ar = {
  common: {
    ok: "موافق",
    cancel: "إلغاء",
    confirm: "تأكيد",
    save: "حفظ",
    delete: "حذف",
    edit: "تعديل",
    done: "تم",
    back: "رجوع",
    close: "إغلاق",
    loading: "جاري التحميل...",
    error: "حدث خطأ",
    retry: "حاول مجددًا",
    submit: "إرسال",
    next: "التالي",
    skip: "تخطي",
    yes: "نعم",
    no: "لا",
    search: "بحث",
    filter: "تصفية",
    clear: "مسح",
    apply: "تطبيق",
    share: "مشاركة",
    copy: "نسخ",
    copied: "تم النسخ!",
    noResults: "لا توجد نتائج",
    optional: "اختياري",
    required: "مطلوب",
    all: "الكل",
    more: "المزيد",
    less: "أقل",
    seeAll: "عرض الكل",
    noData: "لا توجد بيانات",
    refresh: "تحديث",
  },
  auth: {
    login: "تسجيل الدخول",
    register: "إنشاء حساب",
    logout: "تسجيل الخروج",
    email: "البريد الإلكتروني",
    password: "كلمة المرور",
    confirmPassword: "تأكيد كلمة المرور",
    forgotPassword: "نسيت كلمة المرور؟",
    newPassword: "كلمة مرور جديدة",
    phone: "رقم الهاتف",
    otp: "رمز التحقق",
    sendOtp: "إرسال OTP",
    verifyOtp: "التحقق من OTP",
    resendOtp: "إعادة إرسال OTP",
    fullName: "الاسم الكامل",
    createAccount: "إنشاء حساب",
    alreadyHaveAccount: "لديك حساب بالفعل؟",
    dontHaveAccount: "ليس لديك حساب؟",
    welcomeBack: "مرحبًا بعودتك!",
    loginToContinue: "سجّل الدخول للمتابعة",
    createYourAccount: "أنشئ حسابك",
    joinVoxLink: "انضم إلى VoxLink اليوم",
    enterOtp: "أدخل رمز OTP المُرسَل إلى",
    passwordResetSent: "تم إرسال بريد إعادة تعيين كلمة المرور",
    checkEmail: "تحقق من بريدك الإلكتروني للتعليمات",
    passwordChanged: "تم تغيير كلمة المرور بنجاح",
    invalidCredentials: "البريد الإلكتروني أو كلمة المرور غير صحيحة",
    accountDeleted: "تم حذف الحساب بنجاح",
    deleteAccountConfirm: "هل أنت متأكد من أنك تريد حذف حسابك؟ لا يمكن التراجع عن هذا الإجراء.",
  },
  nav: {
    home: "الرئيسية",
    search: "بحث",
    messages: "الرسائل",
    wallet: "المحفظة",
    profile: "الملف الشخصي",
    notifications: "الإشعارات",
  },
  home: {
    greeting: "مرحبًا",
    findHosts: "ابحث عن مضيف",
    topListeners: "أبرز المستمعين",
    trending: "الأكثر رواجًا",
    newHosts: "مضيفون جدد",
    onlineNow: "متصل الآن",
    featuredHosts: "مضيفون مميزون",
    seeAll: "عرض الكل",
    searchPlaceholder: "ابحث عن مضيفين ومواضيع...",
  },
  hosts: {
    host: "مضيف",
    listener: "مستمع",
    online: "متصل",
    offline: "غير متصل",
    busy: "مشغول",
    rating: "التقييم",
    reviews: "التقييمات",
    review: "تقييم",
    coinsPerMinute: "عملة/دقيقة",
    totalMinutes: "إجمالي الدقائق",
    specialties: "التخصصات",
    languages: "اللغات",
    about: "عن",
    callNow: "اتصل الآن",
    audioCall: "مكالمة صوتية",
    videoCall: "مكالمة مرئية",
    sendMessage: "إرسال رسالة",
    talkNow: "تحدث الآن",
    noHostsFound: "لم يتم العثور على مضيفين",
    adjustFilters: "حاول تعديل الفلاتر",
    topRated: "الأعلى تقييمًا",
    viewProfile: "عرض الملف",
    startCall: "بدء المكالمة",
  },
  calls: {
    incoming: "مكالمة واردة",
    outgoing: "جاري الاتصال...",
    ongoing: "في مكالمة",
    ended: "انتهت المكالمة",
    audio: "مكالمة صوتية",
    video: "مكالمة مرئية",
    accept: "قبول",
    decline: "رفض",
    endCall: "إنهاء المكالمة",
    mute: "كتم الصوت",
    unmute: "إلغاء الكتم",
    speaker: "مكبر الصوت",
    flipCamera: "قلب الكاميرا",
    callDuration: "مدة المكالمة",
    callWith: "مكالمة مع",
    rateCall: "قيّم هذه المكالمة",
    callHistory: "سجل المكالمات",
    noCallHistory: "لا يوجد سجل مكالمات",
    callCost: "تكلفة المكالمة",
    perMinute: "في الدقيقة",
    lowBalance: "رصيد العملات منخفض",
    lowBalanceMsg: "رصيدك من العملات منخفض. أعد الشحن للمتابعة.",
    callEnded: "انتهت المكالمة",
    callEndedMsg: "انتهت مكالمتك",
    missed: "فائتة",
    answered: "مُجاب",
    rejected: "مرفوضة",
  },
  chat: {
    messages: "الرسائل",
    newMessage: "رسالة جديدة",
    typeMessage: "اكتب رسالة...",
    send: "إرسال",
    noMessages: "لا توجد رسائل بعد",
    startConversation: "ابدأ محادثة",
    online: "متصل",
    offline: "غير متصل",
    typing: "يكتب...",
    delivered: "تم التسليم",
    read: "مقروء",
    deleteChat: "حذف المحادثة",
    deleteChatConfirm: "هل أنت متأكد من حذف هذه المحادثة؟",
  },
  wallet: {
    wallet: "المحفظة",
    coinBalance: "رصيد العملات",
    coins: "عملات",
    coin: "عملة",
    buyCoins: "شراء عملات",
    coinHistory: "سجل العملات",
    transactions: "المعاملات",
    noTransactions: "لا توجد معاملات بعد",
    purchased: "مشتراة",
    spent: "مُنفَق",
    bonus: "مكافأة",
    refunded: "مسترد",
    withdrawal: "سحب",
    totalSpent: "إجمالي الإنفاق",
    totalPurchased: "إجمالي الشراء",
    popular: "الأكثر شعبية",
    bestValue: "أفضل قيمة",
    bonus_label: "مكافأة",
    recharge: "إعادة شحن",
    choosePackage: "اختر الباقة",
    instantDelivery: "تسليم فوري",
    securePayment: "دفع آمن",
    guaranteed: "ضمان الرضا",
  },
  profile: {
    profile: "الملف الشخصي",
    editProfile: "تعديل الملف",
    myProfile: "ملفي الشخصي",
    name: "الاسم",
    email: "البريد الإلكتروني",
    phone: "الهاتف",
    gender: "الجنس",
    male: "ذكر",
    female: "أنثى",
    other: "آخر",
    country: "البلد",
    bio: "النبذة",
    language: "اللغة",
    settings: "الإعدادات",
    helpCenter: "مركز المساعدة",
    privacy: "سياسة الخصوصية",
    about: "عن VoxLink",
    shareApp: "مشاركة VoxLink",
    rateApp: "قيّم التطبيق",
    logout: "تسجيل الخروج",
    deleteAccount: "حذف الحساب",
    callHistory: "سجل المكالمات",
    joinedOn: "انضم في",
    totalCalls: "إجمالي المكالمات",
    hoursSpent: "الساعات المُقضاة",
  },
  settings: {
    settings: "الإعدادات",
    notifications: "الإشعارات",
    callNotifications: "إشعارات المكالمات",
    messageNotifications: "إشعارات الرسائل",
    promoNotifications: "الإشعارات الترويجية",
    language: "اللغة",
    theme: "المظهر",
    lightMode: "الوضع الفاتح",
    darkMode: "الوضع الداكن",
    systemDefault: "افتراضي النظام",
    privacy: "الخصوصية",
    security: "الأمان",
    changePassword: "تغيير كلمة المرور",
    twoFactor: "التحقق بخطوتين",
    account: "الحساب",
    support: "الدعم",
  },
  payment: {
    checkout: "إتمام الشراء",
    selectPackage: "اختر الباقة",
    paymentMethod: "طريقة الدفع",
    creditCard: "بطاقة ائتمان/خصم",
    paypal: "PayPal",
    googlePay: "Google Pay",
    applePay: "Apple Pay",
    processingPayment: "جاري معالجة الدفع...",
    paymentSuccess: "تمت عملية الدفع بنجاح!",
    paymentFailed: "فشلت عملية الدفع",
    orderSummary: "ملخص الطلب",
    total: "الإجمالي",
    coins: "عملات",
    bonusCoins: "عملات مكافأة",
    tryAgain: "حاول مجددًا",
    secureNote: "جميع المدفوعات مؤمّنة ومشفّرة",
  },
  host: {
    dashboard: "لوحة التحكم",
    totalEarnings: "إجمالي الأرباح",
    thisWeek: "هذا الأسبوع",
    thisMonth: "هذا الشهر",
    totalCalls: "إجمالي المكالمات",
    avgRating: "متوسط التقييم",
    onlineStatus: "حالة الاتصال",
    goOnline: "تسجيل الدخول",
    goOffline: "تسجيل الخروج",
    setBusy: "تعيين كمشغول",
    earnings: "الأرباح",
    withdraw: "سحب",
    withdrawal: "سحب الأرباح",
    minimumWithdraw: "الحد الأدنى 100 عملة",
    enterAmount: "أدخل المبلغ",
    withdrawMethod: "طريقة السحب",
    bankTransfer: "تحويل بنكي",
    upi: "UPI / PayTM",
    paypal: "PayPal",
    accountDetails: "تفاصيل الحساب",
    withdrawSuccess: "تم تقديم طلب السحب",
    withdrawPending: "طلبك قيد المعالجة",
    hostSettings: "إعدادات المضيف",
    availability: "التوفر",
    payoutSettings: "إعدادات الدفع",
    becomeHost: "كن مضيفًا",
    apply: "تقدّم الآن",
    applicationSent: "تم إرسال الطلب!",
    applicationDesc: "سنراجع طلبك ونتواصل معك خلال 2-3 أيام عمل.",
  },
  errors: {
    network: "خطأ في الشبكة. يرجى التحقق من اتصالك.",
    server: "خطأ في الخادم. يرجى المحاولة لاحقًا.",
    unauthorized: "انتهت الجلسة. يرجى تسجيل الدخول مجددًا.",
    notFound: "المورد المطلوب غير موجود.",
    insufficientCoins: "عملات غير كافية. يرجى إعادة الشحن.",
    callFailed: "لا يمكن الاتصال. يرجى المحاولة مجددًا.",
    permissionDenied: "تم رفض الإذن.",
    generic: "حدث خطأ ما. يرجى المحاولة مجددًا.",
  },
};

export default ar;
