// VoxLink — Hindi Strings

const hi = {
  common: {
    ok: "ठीक है",
    cancel: "रद्द करें",
    confirm: "पुष्टि करें",
    save: "सहेजें",
    delete: "हटाएं",
    edit: "संपादित करें",
    done: "हो गया",
    back: "वापस",
    close: "बंद करें",
    loading: "लोड हो रहा है...",
    error: "कुछ गलत हो गया",
    retry: "फिर कोशिश करें",
    submit: "जमा करें",
    next: "अगला",
    skip: "छोड़ें",
    yes: "हाँ",
    no: "नहीं",
    search: "खोजें",
    filter: "फ़िल्टर",
    clear: "साफ़ करें",
    apply: "लागू करें",
    share: "साझा करें",
    copy: "कॉपी करें",
    copied: "कॉपी हो गया!",
    noResults: "कोई परिणाम नहीं मिला",
    optional: "वैकल्पिक",
    required: "ज़रूरी",
    all: "सभी",
    more: "अधिक",
    less: "कम",
    seeAll: "सब देखें",
    noData: "कोई डेटा उपलब्ध नहीं",
    refresh: "रीफ्रेश",
  },

  auth: {
    login: "लॉग इन",
    register: "साइन अप",
    logout: "लॉग आउट",
    email: "ईमेल",
    password: "पासवर्ड",
    confirmPassword: "पासवर्ड की पुष्टि करें",
    forgotPassword: "पासवर्ड भूल गए?",
    newPassword: "नया पासवर्ड",
    phone: "फ़ोन नंबर",
    otp: "सत्यापन कोड",
    sendOtp: "OTP भेजें",
    verifyOtp: "OTP सत्यापित करें",
    resendOtp: "OTP फिर भेजें",
    fullName: "पूरा नाम",
    createAccount: "खाता बनाएं",
    alreadyHaveAccount: "पहले से खाता है?",
    dontHaveAccount: "खाता नहीं है?",
    welcomeBack: "वापस स्वागत है!",
    loginToContinue: "जारी रखने के लिए लॉग इन करें",
    createYourAccount: "अपना खाता बनाएं",
    joinVoxLink: "आज VoxLink से जुड़ें",
    enterOtp: "इस नंबर पर भेजा OTP दर्ज करें",
    passwordResetSent: "पासवर्ड रीसेट ईमेल भेजा गया",
    checkEmail: "निर्देशों के लिए ईमेल जांचें",
    passwordChanged: "पासवर्ड सफलतापूर्वक बदला गया",
    invalidCredentials: "अमान्य ईमेल या पासवर्ड",
    accountDeleted: "खाता सफलतापूर्वक हटाया गया",
    deleteAccountConfirm: "क्या आप वाकई अपना खाता हटाना चाहते हैं? यह क्रिया पूर्ववत नहीं की जा सकती।",
  },

  nav: {
    home: "होम",
    search: "खोजें",
    messages: "संदेश",
    wallet: "वॉलेट",
    profile: "प्रोफ़ाइल",
    notifications: "सूचनाएं",
  },

  home: {
    greeting: "नमस्ते",
    findHosts: "होस्ट खोजें",
    topListeners: "शीर्ष श्रोता",
    trending: "अभी ट्रेंडिंग",
    newHosts: "नए होस्ट",
    onlineNow: "अभी ऑनलाइन",
    featuredHosts: "विशेष होस्ट",
    seeAll: "सब देखें",
    searchPlaceholder: "होस्ट, विषय खोजें...",
  },

  hosts: {
    host: "होस्ट",
    listener: "श्रोता",
    online: "ऑनलाइन",
    offline: "ऑफलाइन",
    busy: "व्यस्त",
    rating: "रेटिंग",
    reviews: "समीक्षाएं",
    review: "समीक्षा",
    coinsPerMinute: "कॉइन/मिनट",
    totalMinutes: "कुल मिनट",
    specialties: "विशेषताएं",
    languages: "भाषाएं",
    about: "के बारे में",
    callNow: "अभी कॉल करें",
    audioCall: "ऑडियो कॉल",
    videoCall: "वीडियो कॉल",
    sendMessage: "संदेश भेजें",
    talkNow: "अभी बात करें",
    noHostsFound: "कोई होस्ट नहीं मिला",
    adjustFilters: "अपने फ़िल्टर समायोजित करें",
    topRated: "शीर्ष रेटेड",
    viewProfile: "प्रोफ़ाइल देखें",
    startCall: "कॉल शुरू करें",
  },

  calls: {
    incoming: "आने वाली कॉल",
    outgoing: "कनेक्ट हो रहा है...",
    ongoing: "कॉल पर",
    ended: "कॉल समाप्त",
    audio: "ऑडियो कॉल",
    video: "वीडियो कॉल",
    accept: "स्वीकार करें",
    decline: "अस्वीकार करें",
    endCall: "कॉल समाप्त करें",
    mute: "म्यूट",
    unmute: "अनम्यूट",
    speaker: "स्पीकर",
    flipCamera: "कैमरा बदलें",
    callDuration: "कॉल अवधि",
    callWith: "के साथ कॉल",
    rateCall: "इस कॉल को रेट करें",
    callHistory: "कॉल इतिहास",
    noCallHistory: "अभी तक कोई कॉल इतिहास नहीं",
    callCost: "कॉल लागत",
    perMinute: "प्रति मिनट",
    lowBalance: "कम कॉइन बैलेंस",
    lowBalanceMsg: "आपके कॉइन कम हैं। जारी रखने के लिए रीचार्ज करें।",
    callEnded: "कॉल समाप्त",
    callEndedMsg: "आपकी कॉल समाप्त हो गई है",
    missed: "मिस्ड",
    answered: "उत्तर दिया",
    rejected: "अस्वीकृत",
  },

  chat: {
    messages: "संदेश",
    newMessage: "नया संदेश",
    typeMessage: "संदेश लिखें...",
    send: "भेजें",
    noMessages: "अभी तक कोई संदेश नहीं",
    startConversation: "बातचीत शुरू करें",
    online: "ऑनलाइन",
    offline: "ऑफलाइन",
    typing: "लिख रहा है...",
    delivered: "डिलीवर",
    read: "पढ़ा",
    deleteChat: "चैट हटाएं",
    deleteChatConfirm: "क्या आप इस बातचीत को हटाना चाहते हैं?",
  },

  wallet: {
    wallet: "वॉलेट",
    coinBalance: "कॉइन बैलेंस",
    coins: "कॉइन",
    coin: "कॉइन",
    buyCoins: "कॉइन खरीदें",
    coinHistory: "कॉइन इतिहास",
    transactions: "लेन-देन",
    noTransactions: "अभी तक कोई लेन-देन नहीं",
    purchased: "खरीदा",
    spent: "खर्च किया",
    bonus: "बोनस",
    refunded: "वापस किया",
    withdrawal: "निकासी",
    totalSpent: "कुल खर्च",
    totalPurchased: "कुल खरीद",
    popular: "सबसे लोकप्रिय",
    bestValue: "सर्वोत्तम मूल्य",
    bonus_label: "बोनस",
    recharge: "रीचार्ज",
    choosePackage: "पैकेज चुनें",
    instantDelivery: "तत्काल डिलीवरी",
    securePayment: "सुरक्षित भुगतान",
    guaranteed: "संतुष्टि की गारंटी",
  },

  profile: {
    profile: "प्रोफ़ाइल",
    editProfile: "प्रोफ़ाइल संपादित करें",
    myProfile: "मेरी प्रोफ़ाइल",
    name: "नाम",
    email: "ईमेल",
    phone: "फ़ोन",
    gender: "लिंग",
    male: "पुरुष",
    female: "महिला",
    other: "अन्य",
    country: "देश",
    bio: "बायो",
    language: "भाषा",
    settings: "सेटिंग्स",
    helpCenter: "सहायता और FAQ",
    privacy: "गोपनीयता नीति",
    about: "VoxLink के बारे में",
    shareApp: "VoxLink शेयर करें",
    rateApp: "ऐप को रेट करें",
    logout: "लॉग आउट",
    deleteAccount: "खाता हटाएं",
    callHistory: "कॉल इतिहास",
    joinedOn: "शामिल हुए",
    totalCalls: "कुल कॉल",
    hoursSpent: "बिताए घंटे",
  },

  settings: {
    settings: "सेटिंग्स",
    notifications: "सूचनाएं",
    callNotifications: "कॉल सूचनाएं",
    messageNotifications: "संदेश सूचनाएं",
    promoNotifications: "प्रचार सूचनाएं",
    language: "भाषा",
    theme: "थीम",
    lightMode: "लाइट मोड",
    darkMode: "डार्क मोड",
    systemDefault: "सिस्टम डिफ़ॉल्ट",
    privacy: "गोपनीयता",
    security: "सुरक्षा",
    changePassword: "पासवर्ड बदलें",
    twoFactor: "दो-कारक प्रमाणीकरण",
    account: "खाता",
    support: "सहायता",
  },

  payment: {
    checkout: "चेकआउट",
    selectPackage: "पैकेज चुनें",
    paymentMethod: "भुगतान विधि",
    creditCard: "क्रेडिट / डेबिट कार्ड",
    paypal: "PayPal",
    googlePay: "Google Pay",
    applePay: "Apple Pay",
    processingPayment: "भुगतान प्रक्रिया में...",
    paymentSuccess: "भुगतान सफल!",
    paymentFailed: "भुगतान विफल",
    orderSummary: "ऑर्डर सारांश",
    total: "कुल",
    coins: "कॉइन",
    bonusCoins: "बोनस कॉइन",
    tryAgain: "फिर कोशिश करें",
    secureNote: "सभी भुगतान सुरक्षित और एन्क्रिप्टेड हैं",
  },

  host: {
    dashboard: "डैशबोर्ड",
    totalEarnings: "कुल कमाई",
    thisWeek: "इस सप्ताह",
    thisMonth: "इस महीने",
    totalCalls: "कुल कॉल",
    avgRating: "औसत रेटिंग",
    onlineStatus: "ऑनलाइन स्थिति",
    goOnline: "ऑनलाइन जाएं",
    goOffline: "ऑफलाइन जाएं",
    setBusy: "व्यस्त सेट करें",
    earnings: "कमाई",
    withdraw: "निकालें",
    withdrawal: "निकासी",
    minimumWithdraw: "न्यूनतम 100 कॉइन",
    enterAmount: "राशि दर्ज करें",
    withdrawMethod: "निकासी विधि",
    bankTransfer: "बैंक ट्रांसफर",
    upi: "UPI / PayTM",
    paypal: "PayPal",
    accountDetails: "खाता विवरण",
    withdrawSuccess: "निकासी अनुरोध सबमिट किया गया",
    withdrawPending: "आपका अनुरोध संसाधित किया जा रहा है",
    hostSettings: "होस्ट सेटिंग्स",
    availability: "उपलब्धता",
    payoutSettings: "पेआउट सेटिंग्स",
    becomeHost: "होस्ट बनें",
    apply: "अभी आवेदन करें",
    applicationSent: "आवेदन भेजा गया!",
    applicationDesc: "हम आपके आवेदन की समीक्षा करेंगे और 2-3 कार्य दिवसों के भीतर वापस आएंगे।",
  },

  errors: {
    network: "नेटवर्क त्रुटि। कृपया अपना कनेक्शन जांचें।",
    server: "सर्वर त्रुटि। कृपया बाद में पुनः प्रयास करें।",
    unauthorized: "सत्र समाप्त। कृपया फिर से लॉग इन करें।",
    notFound: "अनुरोधित संसाधन नहीं मिला।",
    insufficientCoins: "अपर्याप्त कॉइन। कृपया रीचार्ज करें।",
    callFailed: "कॉल कनेक्ट नहीं हो सका। कृपया पुनः प्रयास करें।",
    permissionDenied: "अनुमति अस्वीकृत।",
    generic: "कुछ गलत हो गया। कृपया पुनः प्रयास करें।",
  },
};

export default hi;
